---
dist: xenial

sudo: required

language: python
python: "2.7"

before_install:
 - sudo apt-get update -qq

addons:
  apt:
    packages:
    - python-pip

install:
  # Check ansible version
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - sudo printf '[defaults]\nroles_path=../' > ansible.cfg 

  - ansible-galaxy install indigo-dc.nfs

  - ansible-galaxy install indigo-dc.docker

script:
  
  # Basic role syntax check
  - sudo ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
