---
# tasks file for ansible-role-k3s

- name: get k3s bin
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s.sh

- name: Install k3s server
  command: sh /tmp/k3s.sh --no-deploy traefik
  when: ( mode == "server" )

- name: Copy node token into nfs folder
  command: cp /var/lib/rancher/k3s/server/node-token /root/node-token
  when: ( mode == "server" )

- name: Link kubectl to /usr/bin/kubectl
  file:
    src: /usr/local/bin/kubectl
    dest: /usr/bin/kubectl
    state: link
  when: ( mode == "server" )

- name: Get Helm
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /usr/bin/get-helm-3
    mode: 0777
  when: ( mode == "server" )

- name: Install Helm
  command: /usr/bin/get-helm-3
  when: ( mode == "server" )

- name: Configure dashboard manifest
  template:
    src: templates/kubernetes-dashboard.yaml
    dest: /etc/kubernetes-dashboard.yaml
  when: ( mode == "server" )

- name: install Kubernetes dashboard
  shell: kubectl apply -f /etc/kubernetes-dashboard.yaml
  when: ( mode == "server" )

- name: get the dashboard token
  shell: echo "$(kubectl describe secret -n kubernetes-dashboard kubernetes-dashboard-secret | grep "token:" | awk '{print $2}')"
  register: token
  when: ( mode == "server" )

# - name: Synchronization of k3s node token
#   synchronize:
#     src: /var/lib/rancher/k3s/server/node-token
#     dest: /tmp/node-token
#   delegate_to: "{{ inventory_hostname }}"
#   when: ( mode == "node" )

- name: wait 2 min for flannel to start
  wait_for:
    timeout: 120 
  delegate_to: localhost
  when: ( mode == "node" )

- name: Install k3s node
  shell: K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN=`cat  /mnt/nfs/node-token` sh /tmp/k3s.sh 
  #shell: INSTALL_K3S_EXEC="--docker" K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN=`cat  /mnt/nfs/node-token` sh /tmp/k3s.sh 
  #--node-label {{ node_label }}
  when: ( mode == "node" )

- name: print token
  debug:
    var: token.stdout_lines
  when: ( mode == "server" )
